# [ DataSource Configuration ]
spring:
  jpa: 
    database: postgresql
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/ceylon-spring
    driver-class-name: org.postgresql.Driver
    username: ceylon
    password: ceylon
    
# [ AppServer Configuration Section ]
server: 
  port: 0 
  context-path: /foobar
  
# [ Liquibase ]
liquibase:
  change-log: classpath:/liquibase/db.changelog-master.xml
  enabled: true