# [ DataSource Configuration ]
spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:  
    
# [ AppServer Configuration Section ]
server: 
  port: 0 
  context-path: /foobar
  
# [ Liquibase ]
liquibase:
  change-log: classpath:/liquibase/db.changelog-master.xml
  enabled: true