# [ Zuul Configuration Section ]
server:
  port: ${gateway.service.port:8080}

zuul:
  routes:
    passenger:
      path: /passenger/**
      service-id: passenger
      strip-prefix: false
    flight:
      path: /flight/**
      service-id: flight
      strip-prefix: false
