# [ Zuul Configuration Section ]
server:
  port: ${gateway.service.port:8080}

zuul:
  routes:
    passenger:
      path: /bar/**
      service-id: bar
      strip-prefix: false
    flight:
      path: /foo/**
      service-id: foo
      strip-prefix: false
    reservation:
      path: /foobar/**
      service-id: foobar
      strip-prefix: false